name: Testing Secret

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  authenticate:
    environment: test
    name: "Testing Secrets"
    runs-on: ubuntu-latest
    steps:
      - id: authenticate
        name: Authenticate to GitHub App
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.GH_APP_ID }}
          owner: ${{ github.repository_owner }}
          private-key: ${{ secrets.GH_APP_PEM_FILE }}
          repositories: |
            ${{ github.event.repository.name }}
